### ISSUE TITLE
Release next version to PyPI

### ISSUE THREAD

**Issue by ItsDrike** [python-formate/flake8-dunder-all#48]
Hi, I've noticed that you've fixed the incompatibility with newer flake8 versions due to the 4 letter entry point name, which newer flake8 versions don't like in: 6b530dbed0b999613ff8e5ae495d04292bdb2db5. However this commit is not yet available on PyPI.

Because of this, anyone interested in using this extension has to use flake8 version 4.0.1, or older, which is not ideal, considering flake8 version 6.0.0 is already out. In many cases, newer addons might not even be available for this old flake8 version, forcing people to choose between this extension or the new one they'd like to install (such as `flake8-bandit`).

As a temporary solution for anyone who's also having this issue, you can install `flake8-dunder-all` from latest `master` directly, as `pip` supports installations from git repositories. To do this, you can use: `pip install 'flake8-dunder-all git+https://github.com/python-formate/flake8-dunder-all`.

However even though there is a workaround, this really isn't ideal and a new version should be released instead ASAP.

**Comment by nkukard** [comment]
Would be very nice to see a new version released, I'm sure many would appreciate it greatly :)

**Comment by domdfcoding** [comment]
I have released version 0.3.0 to PyPI
